import { ProductProvider } from "@/context/ProductContex";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex justify-between flex-col`}>
      <ProductProvider>
        <header>
          <Navbar />
        </header>
        
          <main>{children}</main>
        </ProductProvider>
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
